### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by tsktech** [pinglinh/simple_webpack_boiletplate#9]
npm start

> reactjs@1.0.0 start /Users/tsk/newWebSites/wpDev/reactJS
> webpack-dev-server --mode development --open

ℹ ｢wds｣: Project is running at http://localhost:8084/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: af830cf6e1065af1c512
Version: webpack 4.30.0
Time: 915ms
Built at: 05/05/2019 9:33:05 PM
       Asset       Size  Chunks             Chunk Names
./index.html  348 bytes          [emitted]
     main.js    349 KiB    main  [emitted]  main
Entrypoint main = main.js
[0] multi (webpack)-dev-server/client?http://localhost ./src 40 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/events/events.js] 13.3 KiB {main} [built]
[./node_modules/html-entities/index.js] 231 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/node-libs-browser/node_modules/punycode/punycode.js] 14.3 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 8.26 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./src/index.js] 1.36 KiB {main} [built] [failed] [1 error]
    + 11 hidden modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/tsk/newWebSites/wpDev/reactJS/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/tsk/newWebSites/wpDev/reactJS/node_modules/@babel/core/lib/config/partial.js:85:55)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 500 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by DataScientist1** [comment]
ERROR in ./src/index.js 5:9
Module parse failed: Unexpected token (5:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const Index = () => {
>   return <div>Hello React!</div>;
| };
| 

can you please help how to resolve this?
